# Generated by Django 4.0.6 on 2022-07-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminloader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title_name',
            new_name='name',
        ),
    ]
