# Generated by Django 4.0.6 on 2022-07-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminloader', '0002_rename_title_name_title_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='pic',
            new_name='cover',
        ),
    ]
